// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbL8ph7wxjjJYZwoGtawHRwMe2CJUqpXA',
    appId: '1:929465734435:web:c19ababd7ec2985c53e896',
    messagingSenderId: '929465734435',
    projectId: 'app-thuong-mai-ndtt',
    authDomain: 'app-thuong-mai-ndtt.firebaseapp.com',
    databaseURL: 'https://app-thuong-mai-ndtt-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'app-thuong-mai-ndtt.appspot.com',
    measurementId: 'G-NH1H28N6GK',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXqiSr4Y1PzzXsxUKVJQKdG-egjn4gWFE',
    appId: '1:929465734435:ios:fc7306b7f281300453e896',
    messagingSenderId: '929465734435',
    projectId: 'app-thuong-mai-ndtt',
    databaseURL: 'https://app-thuong-mai-ndtt-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'app-thuong-mai-ndtt.appspot.com',
    androidClientId: '929465734435-3c0uk1nn7s8qfnkg3jkli541t1l97u4r.apps.googleusercontent.com',
    iosClientId: '929465734435-smgd4thgd947t9ugtisqsdiej8qj1eis.apps.googleusercontent.com',
    iosBundleId: 'com.example.appThuongMai',
  );
}
